import Head from 'next/head';
import { getAllCharacters } from '@/query/queries';
import { Character } from '@/types/characters';
import Card from '@/components/card/card';
import HomeSection from '@/components/sections/home/home'

export async function getStaticProps() {
  const { data } = await getAllCharacters();

  return {
    props: { 
      ...data,
    },
 };
}

export default function Home() {

  return (
    <>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSection />
    </>
  )
}
